CREATE TABLE financial_period (
    id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    fiscal_year INT NOT NULL,
    fiscal_quarter INT NULL,
    period_type VARCHAR(16) NOT NULL,
    start_date DATE NULL,
    end_date DATE NOT NULL,
    filed_at DATE NOT NULL,
    accession_number VARCHAR(32) NOT NULL,
    form_type VARCHAR(16) NOT NULL,
    source VARCHAR(1024) NOT NULL,
    quality VARCHAR(32) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_financial_period_accession (instrument_id, accession_number, period_type, end_date),
    KEY ix_financial_period_latest (instrument_id, period_type, end_date, filed_at),
    CONSTRAINT fk_financial_period_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id),
    CONSTRAINT chk_financial_period_type CHECK (period_type IN ('QUARTERLY','ANNUAL')),
    CONSTRAINT chk_financial_period_quarter CHECK (fiscal_quarter IS NULL OR fiscal_quarter BETWEEN 1 AND 4)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE financial_fact_observation (
    id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    canonical_metric VARCHAR(64) NULL,
    taxonomy VARCHAR(64) NOT NULL,
    concept VARCHAR(128) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    value_decimal DECIMAL(38,10) NOT NULL,
    period_start DATE NULL,
    period_end DATE NOT NULL,
    filed_at DATE NOT NULL,
    accession_number VARCHAR(32) NOT NULL,
    form_type VARCHAR(16) NOT NULL,
    source VARCHAR(1024) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    quality VARCHAR(32) NOT NULL,
    checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_financial_fact_evidence (instrument_id, taxonomy, concept, unit, period_end, accession_number),
    KEY ix_financial_fact_period (instrument_id, period_end, filed_at),
    CONSTRAINT fk_financial_fact_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE financial_metric_snapshot (
    id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    period_id BINARY(16) NOT NULL,
    metric_code VARCHAR(64) NOT NULL,
    value_decimal DECIMAL(38,10) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    calculation_version VARCHAR(32) NOT NULL,
    quality VARCHAR(32) NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_financial_metric_evidence (instrument_id, period_id, metric_code, evidence_checksum),
    KEY ix_financial_metric_latest (instrument_id, metric_code, data_as_of),
    CONSTRAINT fk_financial_metric_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id),
    CONSTRAINT fk_financial_metric_period FOREIGN KEY (period_id) REFERENCES financial_period (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE financial_health_snapshot (
    id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    period_id BINARY(16) NOT NULL,
    strategy_version VARCHAR(64) NOT NULL,
    config_hash CHAR(64) NOT NULL,
    overall_status VARCHAR(32) NOT NULL,
    growth_status VARCHAR(32) NOT NULL,
    profitability_status VARCHAR(32) NOT NULL,
    cash_flow_status VARCHAR(32) NOT NULL,
    balance_sheet_status VARCHAR(32) NOT NULL,
    dilution_status VARCHAR(32) NOT NULL,
    positives JSON NOT NULL,
    negatives JSON NOT NULL,
    quality VARCHAR(32) NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_financial_health_evidence (instrument_id, period_id, config_hash, evidence_checksum),
    KEY ix_financial_health_latest (instrument_id, data_as_of),
    CONSTRAINT fk_financial_health_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id),
    CONSTRAINT fk_financial_health_period FOREIGN KEY (period_id) REFERENCES financial_period (id),
    CONSTRAINT chk_financial_health_overall CHECK (overall_status IN ('STRONG','HEALTHY','STABLE','WEAKENING','BROKEN','MISSING'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
