CREATE TABLE estimate_observation (
    id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    estimate_type VARCHAR(16) NOT NULL,
    period_type VARCHAR(16) NOT NULL,
    period_end DATE NOT NULL,
    horizon VARCHAR(32) NOT NULL,
    mean_value DECIMAL(28,10) NOT NULL,
    high_value DECIMAL(28,10) NULL,
    low_value DECIMAL(28,10) NULL,
    analyst_count INT NULL,
    data_as_of DATETIME(6) NOT NULL,
    source VARCHAR(64) NOT NULL,
    quality VARCHAR(32) NOT NULL,
    checksum CHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_estimate_observation (instrument_id, estimate_type, period_end, horizon, data_as_of, source),
    KEY ix_estimate_history (instrument_id, estimate_type, period_end, data_as_of),
    CONSTRAINT fk_estimate_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id),
    CONSTRAINT chk_estimate_type CHECK (estimate_type IN ('EPS','REVENUE')),
    CONSTRAINT chk_estimate_period_type CHECK (period_type IN ('QUARTERLY','ANNUAL')),
    CONSTRAINT chk_estimate_analysts CHECK (analyst_count IS NULL OR analyst_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE estimate_revision_snapshot (
    id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    period_end DATE NOT NULL,
    horizon VARCHAR(32) NOT NULL,
    revision_7d VARCHAR(32) NOT NULL,
    revision_30d VARCHAR(32) NOT NULL,
    revision_90d VARCHAR(32) NOT NULL,
    overall_revision VARCHAR(32) NOT NULL,
    eps_change_7d DECIMAL(18,10) NULL,
    eps_change_30d DECIMAL(18,10) NULL,
    eps_change_90d DECIMAL(18,10) NULL,
    revenue_change_7d DECIMAL(18,10) NULL,
    revenue_change_30d DECIMAL(18,10) NULL,
    revenue_change_90d DECIMAL(18,10) NULL,
    analyst_count INT NULL,
    dispersion DECIMAL(18,10) NULL,
    quality VARCHAR(32) NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_estimate_revision_evidence (instrument_id, period_end, horizon, data_as_of, evidence_checksum),
    KEY ix_estimate_revision_latest (instrument_id, data_as_of),
    CONSTRAINT fk_estimate_revision_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id),
    CONSTRAINT chk_estimate_revision_overall CHECK (overall_revision IN ('STRONGLY_POSITIVE','POSITIVE','FLAT','NEGATIVE','STRONGLY_NEGATIVE','MISSING'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
