UPDATE portfolio_analysis_step
SET step_type = 'CHECK_ACTIVE_THESES'
WHERE step_type = 'UPDATE_THESES_EVENTS';

UPDATE portfolio_analysis_step
SET depends_on = 'CHECK_ACTIVE_THESES'
WHERE depends_on = 'UPDATE_THESES_EVENTS';

UPDATE portfolio_analysis_step
SET step_type = 'COUNT_ACTIVE_RECOMMENDATIONS'
WHERE step_type = 'GENERATE_DAILY_DIGEST';

UPDATE portfolio_analysis_step
SET depends_on = 'COUNT_ACTIVE_RECOMMENDATIONS'
WHERE depends_on = 'GENERATE_DAILY_DIGEST';

UPDATE job_run
SET job_type = CASE job_type
    WHEN 'UPDATE_THESES_EVENTS' THEN 'CHECK_ACTIVE_THESES'
    WHEN 'GENERATE_DAILY_DIGEST' THEN 'COUNT_ACTIVE_RECOMMENDATIONS'
    WHEN 'WEEKLY_MEMO' THEN 'COUNT_VALID_RECOMMENDATIONS'
    WHEN 'MONTHLY_REVIEW' THEN 'COUNT_RECENT_SUCCESSFUL_ANALYSES'
    ELSE job_type
END
WHERE job_type IN ('UPDATE_THESES_EVENTS', 'GENERATE_DAILY_DIGEST', 'WEEKLY_MEMO', 'MONTHLY_REVIEW');
