CREATE TABLE market_regime_snapshot (
    id BINARY(16) NOT NULL,
    strategy_version VARCHAR(64) NOT NULL,
    regime_label VARCHAR(32) NOT NULL,
    total_score DOUBLE NOT NULL,
    trend_score DOUBLE NOT NULL,
    momentum_score DOUBLE NOT NULL,
    breadth_score DOUBLE NOT NULL,
    stress_score DOUBLE NOT NULL,
    confidence VARCHAR(32) NOT NULL,
    tactical_cap_five_percent BOOLEAN NOT NULL,
    quality_status VARCHAR(32) NOT NULL,
    inputs_json JSON NOT NULL,
    narratives JSON NOT NULL,
    rule_ids JSON NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_market_regime_evidence (strategy_version, data_as_of, evidence_checksum),
    KEY ix_market_regime_latest (data_as_of, created_at),
    CONSTRAINT chk_market_regime_score CHECK (total_score >= 0 AND total_score <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE portfolio_drawdown_snapshot (
    id BINARY(16) NOT NULL,
    strategy_version VARCHAR(64) NOT NULL,
    current_equity DECIMAL(24,8) NOT NULL,
    high_water_mark DECIMAL(24,8) NOT NULL,
    drawdown_fraction DECIMAL(12,8) NOT NULL,
    drawdown_state VARCHAR(64) NOT NULL,
    source_classification VARCHAR(32) NOT NULL,
    market_driven BOOLEAN NOT NULL,
    spy_return_from_peak DECIMAL(12,8) NOT NULL,
    qqq_return_from_peak DECIMAL(12,8) NOT NULL,
    breadth50 DECIMAL(12,8) NOT NULL,
    stress_level DECIMAL(12,8) NOT NULL,
    position_attribution JSON NOT NULL,
    cluster_attribution JSON NOT NULL,
    confidence VARCHAR(32) NOT NULL,
    quality_status VARCHAR(32) NOT NULL,
    narratives JSON NOT NULL,
    rule_ids JSON NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_drawdown_evidence (strategy_version, data_as_of, evidence_checksum),
    KEY ix_drawdown_latest (data_as_of, created_at),
    CONSTRAINT chk_drawdown_equity CHECK (current_equity >= 0 AND high_water_mark > 0),
    CONSTRAINT chk_drawdown_fraction CHECK (drawdown_fraction >= 0 AND drawdown_fraction <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
