CREATE TABLE etf_dip_event (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    strategy_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    setup_score DOUBLE NOT NULL,
    trigger_count INT NOT NULL,
    portfolio_drawdown DECIMAL(18,10) NOT NULL,
    market_driven BOOLEAN NOT NULL,
    emergency_cash_protected BOOLEAN NOT NULL,
    rule_ids JSON NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    valid_until DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_etf_dip_evidence (user_id, instrument_id, strategy_version, evidence_checksum),
    CONSTRAINT fk_etf_dip_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_etf_dip_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id),
    CONSTRAINT chk_etf_dip_score CHECK (setup_score >= 0 AND setup_score <= 100),
    CONSTRAINT chk_etf_dip_triggers CHECK (trigger_count >= 0 AND trigger_count <= 6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE etf_dip_tranche (
    id BINARY(16) NOT NULL,
    dip_event_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    tranche_number INT NOT NULL,
    reserve_fraction DECIMAL(18,10) NOT NULL,
    planned_amount DECIMAL(24,8) NOT NULL,
    status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    planned_for DATE NOT NULL,
    confirmed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_etf_dip_tranche (dip_event_id, tranche_number),
    UNIQUE KEY uq_etf_dip_idempotency (user_id, idempotency_key),
    CONSTRAINT fk_etf_tranche_event FOREIGN KEY (dip_event_id) REFERENCES etf_dip_event (id),
    CONSTRAINT fk_etf_tranche_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT chk_etf_tranche_number CHECK (tranche_number BETWEEN 1 AND 4),
    CONSTRAINT chk_etf_tranche_fraction CHECK (reserve_fraction > 0 AND reserve_fraction <= 0.30),
    CONSTRAINT chk_etf_tranche_status CHECK (status IN ('PLANNED', 'USER_CONFIRMED', 'SKIPPED', 'EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE cashflow_allocation_snapshot (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    strategy_version VARCHAR(64) NOT NULL,
    allocation_month DATE NOT NULL,
    surplus DECIMAL(24,8) NOT NULL,
    emergency_amount DECIMAL(24,8) NOT NULL,
    broad_core_amount DECIMAL(24,8) NOT NULL,
    tech_core_amount DECIMAL(24,8) NOT NULL,
    international_core_amount DECIMAL(24,8) NOT NULL,
    tactical_reserve_amount DECIMAL(24,8) NOT NULL,
    quality_opportunity_amount DECIMAL(24,8) NOT NULL,
    rule_ids JSON NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cashflow_allocation (user_id, strategy_version, allocation_month, evidence_checksum),
    CONSTRAINT fk_cashflow_allocation_user FOREIGN KEY (user_id) REFERENCES app_user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE active_sleeve_review_snapshot (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    strategy_version VARCHAR(64) NOT NULL,
    review_months INT NOT NULL,
    underperformance_fraction DECIMAL(18,10) NOT NULL,
    drawdown_improved BOOLEAN NOT NULL,
    budget_multiplier DECIMAL(18,10) NOT NULL,
    rule_ids JSON NOT NULL,
    evidence_checksum CHAR(64) NOT NULL,
    data_as_of DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_active_sleeve_review (user_id, strategy_version, review_months, evidence_checksum),
    CONSTRAINT fk_active_sleeve_review_user FOREIGN KEY (user_id) REFERENCES app_user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
